on:
  push

jobs:
  test:
    name: linter and test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
      - name:
        run: go test